### ISSUE TITLE
[bug] 不能匹配图片链接中两头带 <> 的，附解决方案

### ISSUE THREAD

**Issue by rchangl** [yiyungent/hexo-asset-img#9]
如 `![git](<fileName/2023-11-28-15-54-23.png>)` 就不会匹配到

解决方案：

第50行的
`var regExp = RegExp("!\\[(.*?)\\]\\(" + fileName + '/(.+?)\\)', "g");`
改为
`var regExp = RegExp("!\\[(.*?)\\]\\(<?" + fileName + '/(.+?)>?\\)', "g");`

**Comment by rchangl** [comment]
此问题的发现，是由于 VSCode 新版新增了直接粘贴图片的功能，带空格的链接会在两头加上 `<>`

**Comment by yiyungent** [comment]
我刚刚测试了一下，不行啊，

https://replit.com/@yiyungent/hexo-asset-img-test#test.js

这里可以在线测试，我都编写好了，可以试试，我这里没有匹配并替换
